[licenses]
allow = [
  "AGPL-3.0-or-later",
  "MIT",
  "MIT-0",
  "BSL-1.0",
  "Apache-2.0",
  "BSD-3-Clause",
  "ISC",
  "Zlib",
  "BSD-2-Clause",
  "CC0-1.0",
  "Unicode-3.0",
]

[advisories]
ignore = [
  # paste was announced as unmaintained with no explanation or replacement
  # See: https://rustsec.org/advisories/RUSTSEC-2024-0436
  # Bevy relies on this in multiple indirect ways, so ignoring it is the only feasible current solution
  "RUSTSEC-2024-0436",
]

[bans]
skip-tree = ["bevy"]

[sources]
unknown-git = "allow"
